get:
  tags:
    - TimeLog
  summary: 출퇴근 조회
  parameters:
    - in: header
      name: authorization
      schema:
        type: string
      required: true
    - in: query
      name: period
      schema:
        type: string
        description: daily, weekly, monthly
  responses:
    '200':
      description: 성공
      content:
        application/json:
          schema:
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: number
                example: 200
              message:
                type: string
                example: 성공
              data:
                type: array
                items:
                  type: object
                  properties:
                    commuteId:
                      type: number
                      example: 1
                    fromWork:
                      type: string
                      example: '2022-07-28T08:40:59.0000Z'
                    toWork:
                      type: string
                      example: '2022-07-28T18:00:59.000Z'
                    timeWork:
                      type: number
                      example: 9
    '401':
      $ref: '../../openapi.yaml#/components/responses/Unauthorized'
    '503':
      $ref: '../../openapi.yaml#/components/responses/InternalServerError'

post:
  tags:
    - TimeLog
  summary: 출근 등록
  parameters:
    - in: header
      name: authorization
      schema:
        type: string
      required: true
  responses:
    '201':
      $ref: '../../openapi.yaml#/components/responses/CREATED'
    '401':
      $ref: '../../openapi.yaml#/components/responses/Unauthorized'
    '503':
      $ref: '../../openapi.yaml#/components/responses/InternalServerError'
