post:
  tags:
    - Holiday
  summary: 휴가 등록
  parameters:
    - in: header
      name: authorization
      schema:
        type: string
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          properties:
            startDate:
              type: number
              example: 20220510
            endDate:
              type: number
              example: 20220520
  responses:
    '201':
      $ref: '../../openapi.yaml#/components/responses/CREATED'
    '401':
      $ref: '../../openapi.yaml#/components/responses/Unauthorized'
    '503':
      $ref: '../../openapi.yaml#/components/responses/InternalServerError'

get:
  tags:
    - Holiday
  summary: 휴가 전체 조회(자신)
  parameters:
    - in: header
      name: authorization
      schema:
        type: string
      required: true
    - in: query
      name: type
      schema:
        type: string
        description: '0:전체 휴가 조회, 1:승인 휴가 조회, 2: 반려 휴가 조회'
      required: true
  responses:
    '200':
      description: 성공
      content:
        application/json:
          schema:
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: number
                example: 200
              message:
                type: string
                example: 성공
              data:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  startDate:
                    type: string
                    example: '2022-07-28T00:00:00.0000Z'
                  endDate:
                    type: string
                    example: '2022-07-29T00:00:00.0000Z'
                  holidaySum:
                    type: number
                    example: 1
                  user:
                    type: object
                    properties:
                      id:
                        type: number
                        example: 1
                      name:
                        type: string
                        example: 김삐룸
                      email:
                        type: string
                        example: kimbroom@naver.com
    '401':
      $ref: '../../openapi.yaml#/components/responses/Unauthorized'
    '503':
      $ref: '../../openapi.yaml#/components/responses/InternalServerError'
