get:
  tags:
    - Department
  summary: 부서 전체 조회
  parameters:
    - in: header
      name: authorization
      schema:
        type: string
      required: true
  responses:
    '200':
      description: 성공
      content:
        application/json:
          schema:
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: number
                example: 200
              message:
                type: string
                example: 성공
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                      description: 유저 id
                    name:
                      type: string
                      example: 김삐룸
                    companyDepartment:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 개발
    '401':
      $ref: '../../openapi.yaml#/components/responses/Unauthorized'
    '503':
      $ref: '../../openapi.yaml#/components/responses/InternalServerError'

post:
  tags:
    - Department
  summary: 부서 생성
  parameters:
    - in: header
      name: authorization
      schema:
        type: string
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          properties:
            name:
              type: string
              example: 기획
  responses:
    '201':
      $ref: '../../openapi.yaml#/components/responses/CREATED'
    '401':
      description: 인증 안됨
    '404':
      description: 필요한 값이 없음
    '503':
      $ref: '../../openapi.yaml#/components/responses/InternalServerError'
