post:
  tags:
    - User
  summary: 로그인
  requestBody:
    required: true
    content:
      application/json:
        schema:
          properties:
            email:
              type: string
              example: 'hello@naver.com'
            password:
              type: string
              example: '1234!'
  responses:
    '200':
      description: 성공
      content:
        application/json:
          schema:
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: number
                example: 200
              message:
                type: string
                example: 성공
              accessToken:
                type: string
                example: accessToken
    '403':
      description: 존재하지 않는 회원정보
    '503':
      $ref: '../../openapi.yaml#/components/responses/InternalServerError'
